schema_version = "1.0.0"

id = "j_curves"
version = "1.0.0"
name = "J.CURVES"
tagline = "Simplify curve workflow for stylized and hair-cards hair"
maintainer = "J.STILL"
type = "add-on"
website = "https://github.com/JST1LL/JCURVES"
tags = ["Add Curve", "Geometry Nodes", "Material"]

blender_version_min = "4.5.0"

license = [
  "SPDX:GPL-3.0-or-later",
]

copyright = [
	"2025 Jane Still",
]

paths = [
	"/blendfile/"
]

paths_exclude_pattern = [
	"__pycache__/",
	"/.git/",
	"/*.zip",
]